# Generated by Django 3.2.12 on 2022-06-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo_User',
        ),
    ]
