# Generated by Django 3.2.12 on 2022-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=45)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('price', models.FloatField()),
                ('special_price', models.FloatField()),
                ('special_price_from', models.DateField()),
                ('special_price_to', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('meta_title', models.CharField(max_length=45)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('status1', models.BooleanField(default=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateField()),
                ('modify_by', models.IntegerField()),
                ('modify_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
