# Generated by Django 3.2.12 on 2022-06-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='order_details',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products'),
        ),
        migrations.AlterField(
            model_name='product_attribute_assoc',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products'),
        ),
    ]
