# Generated by Django 3.2.12 on 2022-06-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_auto_20220624_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
