# Generated by Django 3.2.12 on 2022-06-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_auto_20220624_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'product'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
