# Generated by Django 3.2.12 on 2022-06-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_auto_20220624_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
