# Generated by Django 3.2.12 on 2022-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_auto_20220627_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
