# Generated by Django 3.2.12 on 2022-06-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_alter_user_register_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='contactus',
        ),
        migrations.RenameModel(
            old_name='Coupons_used',
            new_name='couponsused',
        ),
        migrations.RenameModel(
            old_name='Email_template',
            new_name='emailtemplate',
        ),
        migrations.RenameModel(
            old_name='Manage_user',
            new_name='manageuser',
        ),
        migrations.RenameModel(
            old_name='Order_details',
            new_name='orderdetails',
        ),
        migrations.RenameModel(
            old_name='Payment_gateway',
            new_name='paymentgateway',
        ),
        migrations.RenameModel(
            old_name='Product_attribute_assoc',
            new_name='productattributeassoc',
        ),
        migrations.RenameModel(
            old_name='Product_attributes',
            new_name='productattributes',
        ),
        migrations.RenameModel(
            old_name='Product_attribute_value',
            new_name='productattributevalue',
        ),
        migrations.RenameModel(
            old_name='Product_category',
            new_name='productcategory',
        ),
        migrations.RenameModel(
            old_name='Product_images',
            new_name='productimages',
        ),
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='subcategory',
        ),
        migrations.RenameModel(
            old_name='User_address',
            new_name='useraddress',
        ),
        migrations.RenameModel(
            old_name='User_info',
            new_name='userinfo',
        ),
        migrations.RenameModel(
            old_name='User_login',
            new_name='userlogin',
        ),
        migrations.RenameModel(
            old_name='User_order',
            new_name='userorder',
        ),
        migrations.RenameModel(
            old_name='User_register',
            new_name='userregister',
        ),
        migrations.RenameModel(
            old_name='User_wish_list',
            new_name='userwishlist',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contactus', 'verbose_name_plural': 'contactus'},
        ),
        migrations.AlterModelOptions(
            name='couponsused',
            options={'verbose_name': 'couponused', 'verbose_name_plural': 'couponused'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'email template', 'verbose_name_plural': 'email template'},
        ),
        migrations.AlterModelOptions(
            name='manageuser',
            options={'verbose_name': 'manage user', 'verbose_name_plural': 'manage user'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'order details', 'verbose_name_plural': 'order details'},
        ),
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name': 'payment gateway', 'verbose_name_plural': 'payment gateway'},
        ),
        migrations.AlterModelOptions(
            name='productattributeassoc',
            options={'verbose_name': 'product attribute assoc', 'verbose_name_plural': 'product attribute assoc'},
        ),
        migrations.AlterModelOptions(
            name='productattributes',
            options={'verbose_name': 'product attributes', 'verbose_name_plural': 'product attributes'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'product attribute value', 'verbose_name_plural': 'product attribute value'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'product category'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product images', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategory'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'user address', 'verbose_name_plural': 'user address'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'userinfo', 'verbose_name_plural': 'userinfo'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'User login', 'verbose_name_plural': 'User login'},
        ),
        migrations.AlterModelOptions(
            name='userorder',
            options={'verbose_name': 'userorder', 'verbose_name_plural': 'userorder'},
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'verbose_name': 'User register', 'verbose_name_plural': 'User register'},
        ),
        migrations.AlterModelOptions(
            name='userwishlist',
            options={'verbose_name': 'user wish list', 'verbose_name_plural': 'user wish list'},
        ),
    ]
