# Generated by Django 3.2.12 on 2022-06-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0036_auto_20220629_0551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='brands',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='categorys',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='products',
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'brands', 'verbose_name_plural': 'brands'},
        ),
    ]
