# Generated by Django 3.2.12 on 2022-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0037_auto_20220629_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product_image',
            field=models.ImageField(upload_to='media/photos/images'),
        ),
    ]
