# Generated by Django 3.2.12 on 2022-06-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_alter_productimages_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='images',
            field=models.ImageField(upload_to='media'),
        ),
    ]
