# Generated by Django 3.2.12 on 2022-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_products_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='filterprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('100 TO 200', '100 TO 200'), ('200 TO 300', '200 TO 300'), ('300 TO 400', '300 TO 400'), ('400 TO 500', '400 TO 500'), ('500 TO 600', '500 TO 600')], max_length=60)),
            ],
        ),
    ]
