# Generated by Django 3.2.12 on 2022-06-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_filterprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='filterprice',
            new_name='filterprices',
        ),
    ]
