# Generated by Django 3.2.12 on 2022-06-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_products_filter_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Availability',
        ),
    ]
