# Generated by Django 3.2.12 on 2022-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_remove_products_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=100, null=True),
        ),
    ]
