# Generated by Django 3.2.12 on 2022-06-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_alter_filterprices_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products')),
            ],
        ),
    ]
