# Generated by Django 3.2.12 on 2022-07-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'images', 'verbose_name_plural': 'images'},
        ),
        migrations.RenameField(
            model_name='images',
            old_name='products',
            new_name='product',
        ),
    ]
