# Generated by Django 3.2.12 on 2022-07-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0054_alter_products_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponsused',
            options={'verbose_name': 'coupon Used', 'verbose_name_plural': 'coupon Used'},
        ),
        migrations.AlterModelOptions(
            name='manageuser',
            options={'verbose_name': 'manage User', 'verbose_name_plural': 'manage User'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'order Details', 'verbose_name_plural': 'order Details'},
        ),
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name': 'payment Gateway', 'verbose_name_plural': 'payment Gateway'},
        ),
        migrations.AlterModelOptions(
            name='productattributeassoc',
            options={'verbose_name': 'product Attribute Assoc', 'verbose_name_plural': 'product Attribute Assoc'},
        ),
        migrations.AlterModelOptions(
            name='productattributes',
            options={'verbose_name': 'product Attributes', 'verbose_name_plural': 'product Attributes'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'product Attribute Value', 'verbose_name_plural': 'product Attribute Value'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product Category', 'verbose_name_plural': 'product Category'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Images', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'user Address', 'verbose_name_plural': 'user Address'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'User Login', 'verbose_name_plural': 'User Login'},
        ),
        migrations.AlterModelOptions(
            name='userorder',
            options={'verbose_name': 'user Order', 'verbose_name_plural': 'user Order'},
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'verbose_name': 'User Register', 'verbose_name_plural': 'User Register'},
        ),
        migrations.AlterField(
            model_name='products',
            name='filter_price',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.filterprices'),
        ),
    ]
