# Generated by Django 3.2.12 on 2022-07-09 12:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0056_alter_filterprices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterprices',
            name='price',
            field=models.CharField(choices=[('100 TO 199', '100 TO 199'), ('200 TO 299', '200 TO 299'), ('300 TO 399', '300 TO 399'), ('400 TO 499', '400 TO 499'), ('500 TO 600', '500 TO 600')], max_length=60),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/order/image')),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
