# Generated by Django 3.2.12 on 2022-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0060_auto_20220711_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=10000),
        ),
    ]
