# Generated by Django 3.2.12 on 2022-07-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0062_auto_20220714_0739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
