# Generated by Django 3.2.12 on 2022-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0069_auto_20220719_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(max_length=45),
        ),
    ]
