# Generated by Django 3.2.12 on 2022-06-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220607_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_order',
            field=models.BooleanField(default=False, verbose_name='Is order'),
        ),
    ]
