# Generated by Django 3.2.12 on 2022-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
    ]
